[package]
name = "{{ package_name }}_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "_{{ package_name }}_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
